-- =============================================
-- VIDEO MANAGEMENT SYSTEM - SUPABASE SCHEMA
-- =============================================

-- Tabla: videos
CREATE TABLE IF NOT EXISTS videos (
    id TEXT PRIMARY KEY, -- Usamos TEXT porque el ID viene del filename o generated by frontend
    title TEXT NOT NULL,
    duration NUMERIC, -- Duración en segundos
    thumbnail TEXT,
    compressed_size NUMERIC,
    original_size NUMERIC,
    transcription JSONB DEFAULT '{}'::jsonb,
    summary JSONB DEFAULT '{}'::jsonb,
    parts TEXT[] DEFAULT '{}', -- Array de nombres de archivo de las partes
    youtube_link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Row Level Security
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad (RLS)

-- 1. Permitir lectura publica (para que el dashboard pueda ver los videos)
CREATE POLICY "Public Read Videos"
ON videos FOR SELECT
USING (true);

-- 2. Permitir inserción autenticada (para cuando el usuario sube videos)
CREATE POLICY "Authenticated Insert Videos"
ON videos FOR INSERT
TO authenticated
WITH CHECK (true);

-- 3. Permitir actualización autenticada (para editar metadata)
CREATE POLICY "Authenticated Update Videos"
ON videos FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- 4. Permitir eliminación autenticada
CREATE POLICY "Authenticated Delete Videos"
ON videos FOR DELETE
TO authenticated
USING (true);

-- Storage Bucket configuration (Optional, if not exists)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('videos', 'videos', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
CREATE POLICY "Public Access Video Bucket"
ON storage.objects FOR SELECT
USING ( bucket_id = 'videos' );

CREATE POLICY "Authenticated Upload Video Bucket"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'videos' );

CREATE POLICY "Authenticated Delete Video Bucket"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'videos' );
